export const WHITE_COLOR = "#f0d9b5";
export const BLACK_COLOR = "#b58863";

export interface Square {
  current_x: number;
  current_y: number;
  initial_x: number;
  initial_y: number;
  piece: string;
  image: string;
  color: string;
}

export const initialBoard: Square[][] = [
  // Row 1 (Black back rank)
  [
    {
      current_x: 0,
      current_y: 0,
      initial_x: 0,
      initial_y: 0,
      piece: "rook",
      image: "/black_rook.svg",
      color: "white",
    },
    {
      current_x: 1,
      current_y: 0,
      initial_x: 1,
      initial_y: 0,
      piece: "knight",
      image: "/black_knight.svg",
      color: "black",
    },
    {
      current_x: 2,
      current_y: 0,
      initial_x: 2,
      initial_y: 0,
      piece: "bishop",
      image: "/black_bishop.svg",
      color: "white",
    },
    {
      current_x: 3,
      current_y: 0,
      initial_x: 3,
      initial_y: 0,
      piece: "queen",
      image: "/black_queen.svg",
      color: "black",
    },
    {
      current_x: 4,
      current_y: 0,
      initial_x: 4,
      initial_y: 0,
      piece: "king",
      image: "/black_king.svg",
      color: "white",
    },
    {
      current_x: 5,
      current_y: 0,
      initial_x: 5,
      initial_y: 0,
      piece: "bishop",
      image: "/black_bishop.svg",
      color: "black",
    },
    {
      current_x: 6,
      current_y: 0,
      initial_x: 6,
      initial_y: 0,
      piece: "knight",
      image: "/black_knight.svg",
      color: "white",
    },
    {
      current_x: 7,
      current_y: 0,
      initial_x: 7,
      initial_y: 0,
      piece: "rook",
      image: "/black_rook.svg",
      color: "black",
    },
  ],
  // Row 2 (Black pawns)
  [
    {
      current_x: 0,
      current_y: 1,
      initial_x: 0,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "black",
    },
    {
      current_x: 1,
      current_y: 1,
      initial_x: 1,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "white",
    },
    {
      current_x: 2,
      current_y: 1,
      initial_x: 2,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "black",
    },
    {
      current_x: 3,
      current_y: 1,
      initial_x: 3,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "white",
    },
    {
      current_x: 4,
      current_y: 1,
      initial_x: 4,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "black",
    },
    {
      current_x: 5,
      current_y: 1,
      initial_x: 5,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "white",
    },
    {
      current_x: 6,
      current_y: 1,
      initial_x: 6,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "black",
    },
    {
      current_x: 7,
      current_y: 1,
      initial_x: 7,
      initial_y: 1,
      piece: "pawn",
      image: "/black_pawn.svg",
      color: "white",
    },
  ],
  // Rows 3–6 (Empty rows)
  ...Array.from({ length: 4 }, (_, rowIndex) =>
    Array.from({ length: 8 }, (_, colIndex) => ({
      current_x: colIndex,
      current_y: rowIndex + 2,
      initial_x: colIndex,
      initial_y: rowIndex + 2,
      piece: "",
      image: "",
      color: (rowIndex + colIndex) % 2 === 0 ? "white" : "black",
    }))
  ),
  // Row 7 (White pawns)
  [
    {
      current_x: 0,
      current_y: 6,
      initial_x: 0,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "white",
    },
    {
      current_x: 1,
      current_y: 6,
      initial_x: 1,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "black",
    },
    {
      current_x: 2,
      current_y: 6,
      initial_x: 2,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "white",
    },
    {
      current_x: 3,
      current_y: 6,
      initial_x: 3,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "black",
    },
    {
      current_x: 4,
      current_y: 6,
      initial_x: 4,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "white",
    },
    {
      current_x: 5,
      current_y: 6,
      initial_x: 5,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "black",
    },
    {
      current_x: 6,
      current_y: 6,
      initial_x: 6,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "white",
    },
    {
      current_x: 7,
      current_y: 6,
      initial_x: 7,
      initial_y: 6,
      piece: "pawn",
      image: "/white_pawn.svg",
      color: "black",
    },
  ],
  // Row 8 (White back rank)
  [
    {
      current_x: 0,
      current_y: 7,
      initial_x: 0,
      initial_y: 7,
      piece: "rook",
      image: "/white_rook.svg",
      color: "black",
    },
    {
      current_x: 1,
      current_y: 7,
      initial_x: 1,
      initial_y: 7,
      piece: "knight",
      image: "/white_knight.svg",
      color: "white",
    },
    {
      current_x: 2,
      current_y: 7,
      initial_x: 2,
      initial_y: 7,
      piece: "bishop",
      image: "/white_bishop.svg",
      color: "black",
    },
    {
      current_x: 3,
      current_y: 7,
      initial_x: 3,
      initial_y: 7,
      piece: "queen",
      image: "/white_queen.svg",
      color: "white",
    },
    {
      current_x: 4,
      current_y: 7,
      initial_x: 4,
      initial_y: 7,
      piece: "king",
      image: "/white_king.svg",
      color: "black",
    },
    {
      current_x: 5,
      current_y: 7,
      initial_x: 5,
      initial_y: 7,
      piece: "bishop",
      image: "/white_bishop.svg",
      color: "white",
    },
    {
      current_x: 6,
      current_y: 7,
      initial_x: 6,
      initial_y: 7,
      piece: "knight",
      image: "/white_knight.svg",
      color: "black",
    },
    {
      current_x: 7,
      current_y: 7,
      initial_x: 7,
      initial_y: 7,
      piece: "rook",
      image: "/white_rook.svg",
      color: "white",
    },
  ],
];
